### ISSUE TITLE
Cannot install from atom > Settings > Install

### ISSUE THREAD

**Issue by Yajo** [davidcelis/language-fish-shell#7]
I get this error:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.6
gyp info using node@4.4.5 | linux | x64
gyp ERR! install error 
gyp ERR! stack Error: Invalid version number: undefined
gyp ERR! stack     at install (/usr/lib/node_modules/node-gyp/lib/install.js:51:21)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/lib/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at run (/usr/lib/node_modules/node-gyp/bin/node-gyp.js:72:30)
gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/node-gyp/bin/node-gyp.js:133:1)
gyp ERR! stack     at Module._compile (module.js:409:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:416:10)
gyp ERR! stack     at Module.load (module.js:343:32)
gyp ERR! stack     at Function.Module._load (module.js:300:12)
gyp ERR! stack     at Function.Module.runMain (module.js:441:10)
gyp ERR! stack     at startup (node.js:139:18)
gyp ERR! System Linux 4.5.6-200.fc23.x86_64
gyp ERR! command "/usr/lib/node_modules/atom-package-manager/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=undefined" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /home/yajo/.atom
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
```

**Comment by brj** [comment]
Seems more like an Atom error to me :)

**Comment by Yajo** [comment]
Indeed https://github.com/atom/settings-view/issues/766#issuecomment-233382832
